// Generated by CoffeeScript 1.3.3
(function() {
  var LeoAccess, root;

  root = window;

  LeoAccess = (function() {

    function LeoAccess() {
      this.nodes = {};
    }

    LeoAccess.prototype.opendoc = function(url) {
      var _this = this;
      return $.getJSON(url, function(data) {
        var n, _i, _len, _ref;
        console.log("got json! ");
        _ref = data.nodes;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          n = _ref[_i];
          _this.nodes[n.gnx] = {
            b: n.b,
            h: n.h,
            children: n.children
          };
          console.log("Got h " + _this.nodes[n.gnx].h);
        }
        _this.nodes[""] = {
          b: "hidden root",
          h: "hidden root",
          children: data.top
        };
        return _this.showSubtree("");
      });
    };

    LeoAccess.prototype.showSubtree = function(parentGnx) {
      var $n, $r, chignx, chin, n, _i, _len, _ref;
      n = this.nodes[parentGnx];
      $r = $("#lchildren");
      $r.empty();
      console.log("Show subtree for " + parentGnx);
      _ref = n.children;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        chignx = _ref[_i];
        chin = this.nodes[chignx];
        console.log("h = " + chin.h);
        $n = $('<li><a href=""/>' + chin.h + '</li>');
        console.log("Appended " + $n);
        $r.append($n);
      }
      return $r.listview('refresh');
    };

    return LeoAccess;

  })();

  console.log("Parsing");

  root.LeoAccess = LeoAccess;

  $(document).ready(function() {
    console.log("Start dl");
    root.la = new LeoAccess();
    return root.la.opendoc("test_doc.leo.json");
  });

}).call(this);
