// Generated by CoffeeScript 1.3.3
(function() {
  var LeoAccess, root;

  root = window;

  LeoAccess = (function() {

    function LeoAccess() {
      var _this = this;
      this.nodes = {};
      this.parentgnx = "";
      $("#btnback").click(function() {
        console.log("Click back");
        return _this.showSubtree(_this.parentgnx);
      });
    }

    LeoAccess.prototype.opendoc = function(url) {
      var _this = this;
      return $.getJSON(url, function(data) {
        var n, _i, _len, _ref;
        console.log("got json! ");
        _ref = data.nodes;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          n = _ref[_i];
          _this.nodes[n.gnx] = {
            b: n.b,
            h: n.h,
            children: n.children
          };
          console.log("Got h " + _this.nodes[n.gnx].h);
        }
        _this.nodes[""] = {
          b: "hidden root",
          h: "hidden root",
          children: data.top
        };
        return _this.showSubtree("");
      });
    };

    LeoAccess.prototype.showSubtree = function(parentGnx) {
      var $a, $b, $n, $r, chignx, chin, n, that, _i, _len, _ref;
      n = this.nodes[parentGnx];
      $r = $("#lchildren");
      that = this;
      $r.empty();
      $b = $("#bodytext");
      $b.text(n.b);
      $("#hstring").text(n.h);
      console.log("Show subtree for " + parentGnx);
      _ref = n.children;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        chignx = _ref[_i];
        chin = this.nodes[chignx];
        console.log("h = " + chin.h);
        $n = $('<li><a href="#"/>' + chin.h + '</li>');
        $a = $n.find("a");
        $a.data("gnx", chignx);
        $a.click(function() {
          var gnx;
          console.log($(this));
          gnx = $(this).data("gnx");
          that.parentgnx = parentGnx;
          return that.showSubtree(gnx);
        });
        console.log("Appended " + $n);
        $r.append($n);
      }
      return $r.listview('refresh');
    };

    return LeoAccess;

  })();

  console.log("Parsing");

  $(document).ready(function() {
    console.log("Start dl");
    root.la = new LeoAccess();
    return root.la.opendoc("test_doc.leo.json");
  });

}).call(this);
