// Generated by CoffeeScript 1.3.3
(function() {
  var LeoAccess, root;

  root = window;

  LeoAccess = (function() {

    function LeoAccess() {
      var _this = this;
      this.nodes = {};
      this.parentgnx = "";
      this.pstack = [];
      $("#btnback").click(function() {
        console.log("Click back");
        return _this.goBack();
      });
      $("#btnflat").click(function() {
        return _this.goFlat();
      });
    }

    LeoAccess.prototype.walkSubtree = function(n, f) {
      var chignx, chin, _i, _len, _ref, _results;
      _ref = n.children;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        chignx = _ref[_i];
        chin = this.nodes[chignx];
        f(chin);
        _results.push(this.walkSubtree(chin, f));
      }
      return _results;
    };

    LeoAccess.prototype.goFlat = function() {
      var $ul,
        _this = this;
      console.log("Flat view!");
      $ul = $("<ul>");
      $.mobile.changePage($("#flatnodespage"));
      this.walkSubtree(this.nodes[""], function(n) {
        var $li, h;
        console.log("seen " + n.h);
        h = n.h;
        $li = $("<li>").text(n.h).data("gnx", n.gnx);
        return $ul.append($li);
      });
      return $("#flatlist").empty().append($ul);
    };

    LeoAccess.prototype.isTop = function() {
      return this.pstack.length === 0;
    };

    LeoAccess.prototype.goTop = function() {
      this.pstack = [];
      this.parentgnx = "";
      this.showSubtree("");
      $("#btnback").hide();
      $("#bodytext").hide();
      this.updateCrumb();
      return $("#hstring").text("Leo Reader");
    };

    LeoAccess.prototype.drillTo = function(gnx) {
      if (this.isTop()) {
        $("#btnback").show();
        $('#bodytext').show();
      }
      this.pstack.push(this.parentgnx);
      this.parentgnx = gnx;
      this.showSubtree(gnx);
      return this.updateCrumb();
    };

    LeoAccess.prototype.updateCrumb = function() {
      var allgnx, cs, gnx, hs;
      allgnx = this.pstack.slice(1);
      hs = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = allgnx.length; _i < _len; _i++) {
          gnx = allgnx[_i];
          _results.push('<a href="#" data-role="button">' + this.nodes[gnx].h.slice(0, 40) + '</a>');
        }
        return _results;
      }).call(this);
      hs.reverse();
      cs = hs.join(" > ");
      $("#breadcrumb").html(">" + cs);
      return hs;
    };

    LeoAccess.prototype.goBack = function() {
      var newp;
      if (this.pstack.length === 1) {
        this.goTop();
        return;
      }
      newp = this.pstack.pop();
      this.parentgnx = newp;
      this.showSubtree(newp);
      return this.updateCrumb();
    };

    LeoAccess.prototype.opendoc = function(url) {
      var _this = this;
      return $.getJSON(url, function(data) {
        var n, _i, _len, _ref;
        console.log("got json! ");
        _ref = data.nodes;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          n = _ref[_i];
          _this.nodes[n.gnx] = {
            b: n.b,
            h: n.h,
            gnx: n.gnx,
            children: n.children
          };
        }
        _this.nodes[""] = {
          b: "hidden root",
          h: "hidden root",
          gnx: "",
          children: data.top
        };
        _this.goTop("");
        return $.mobile.hidePageLoadingMsg();
      });
    };

    LeoAccess.prototype.showSubtree = function(parentGnx) {
      var $a, $b, $n, $r, chignx, chin, n, that, _i, _len, _ref;
      n = this.nodes[parentGnx];
      $r = $("#lchildren");
      that = this;
      $r.empty();
      $b = $("#bodytext");
      $b.text(n.b);
      $("#hstring").text(n.h);
      console.log("Show subtree for " + parentGnx);
      _ref = n.children;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        chignx = _ref[_i];
        chin = this.nodes[chignx];
        console.log("h = " + chin.h);
        $n = $('<li><a href="#">' + chin.h + '</a></li>');
        $a = $n.find("a");
        $a.data("gnx", chignx);
        $a.click(function() {
          var gnx;
          gnx = $(this).data("gnx");
          return that.drillTo(gnx);
        });
        $r.append($n);
      }
      return $r.listview('refresh');
    };

    return LeoAccess;

  })();

  $(document).ready(function() {
    console.log("Start dl");
    root.la = new LeoAccess();
    $.mobile.showPageLoadingMsg();
    return root.la.opendoc("test_doc.leo.json");
  });

}).call(this);
